### ISSUE TITLE
Updates and cleanup for Public Launch Milestone.

### ISSUE THREAD

**Issue by korymath** [kylemath/EEGEdu#96]
There are a few changes which should be made before this repository goes public:

- [x] Update the README.md - Done with #94 
- [x] Update the CONTRIBUTING.md - Done with #95 
- [x] (@kylemath -- you'll need to do this as the repo owner) -- Add short description and [topics](https://help.github.com/en/github/administering-a-repository/classifying-your-repository-with-topics) to the GitHub Repo.
- [x] Will we be making the repository public? *YES*. I do not think we need to, but there may be some benefit of doing so? 
- [x] Clean up stale branches that are not works in progress.
- [x] Add logo, screenshots to the README.md
- [x] Remove stale code and references
- [ ] Do we want to write up a blog post about the software? 
- [ ] Do we want to write a tutorial on how it might be used? 
- [ ] Will we be pushing it to folks on NeuroTechX? 
- [ ] Do you want to post it on HackerNews / Reddit / Twitter additionally?
- [x] Attribution for images on the website itself should be included as captions on the images.
- [ ] Do we want a Google form to collect user feedback of EEGEdu? Something which will help us collect comments in a centralized place rather than a collection of emails/tweets/face to face comments?

**Comment by korymath** [comment]
Gone public!
